config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :characters

      resources :actors

      resources :bookmarks

      resources :reviews

      resources :users

      resources :directors

      resources :movies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "movies#index"
  resources :characters
  resources :actors
  resources :bookmarks
  resources :reviews
  resources :users
  devise_for :directors
  resources :directors
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/director.rb
class Director < ApplicationRecord
  include JwtToken
  # Direct associations

  has_many   :reviews,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    created_at
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/directors_controller.rb
class Api::V1::DirectorsController < Api::V1::GraphitiController
  def index
    directors = DirectorResource.all(params)
    respond_with(directors)
  end

  def show
    director = DirectorResource.find(params)
    respond_with(director)
  end

  def create
    director = DirectorResource.build(params)

    if director.save
      render jsonapi: director, status: :created
    else
      render jsonapi_errors: director
    end
  end

  def update
    director = DirectorResource.find(params)

    if director.update_attributes
      render jsonapi: director
    else
      render jsonapi_errors: director
    end
  end

  def destroy
    director = DirectorResource.find(params)

    if director.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: director
    end
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: %i[show edit update destroy]

  def index
    @directors = Director.page(params[:page]).per(10)
  end

  def show
    @review = Review.new
  end

  def new
    @director = Director.new
  end

  def edit; end

  def create
    @director = Director.new(director_params)

    if @director.save
      redirect_to @director, notice: "Director was successfully created."
    else
      render :new
    end
  end

  def update
    if @director.update(director_params)
      redirect_to @director, notice: "Director was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @director.destroy
    redirect_to directors_url, notice: "Director was successfully destroyed."
  end

  private

  def set_director
    @director = Director.find(params[:id])
  end

  def director_params
    params.require(:director).permit(:dob, :name, :bio, :image,
                                     :number_of_films)
  end
end

app/views/directors/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Director #<%= director.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Dob</dt>
      <dd><%= director.dob %></dd>

      <dt>Name</dt>
      <dd><%= director.name %></dd>

      <dt>Bio</dt>
      <dd><%= director.bio %></dd>

      <dt>Image</dt>
      <dd><%= director.image %></dd>

      <dt>Number of films</dt>
      <dd><%= director.number_of_films %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back director, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_director_url(director), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to director, method: :delete, data: { confirm: "Do you really want to delete this director?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(director.updated_at) %> ago
  </div>
</div>

app/views/directors/_director_reviews.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Reviews

    <a data-toggle="collapse" href="#director_reviews_new_form">
      Add review
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @director.reviews.each do |review| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to review, review %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="director_reviews_new_form">
        <%= render partial: "directors/director_reviews_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/directors/_director_reviews_new_form.html.erb
<%= form_with(model: @review, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :stars %>

    <%= f.text_field :stars, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :review_text %>

    <%= f.text_field :review_text, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :movie_id %>

    <%= f.collection_select :movie_id, Movie.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :director_id, value: @director.id %>

  <%= f.submit "Create review", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/directors/_form.html.erb
<% was_validated = director.errors.any? %>

<%= form_with(model: director, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% dob_class = "form-control" %>
    <% dob_was_invalid = director.errors.include?(:dob) %>

    <% if was_validated %>
      <% if dob_was_invalid %>
        <% dob_class << " is-invalid" %>
      <% else %>
        <% dob_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dob %>
    <%= f.date_select :dob, class: dob_class, placeholder: "Enter dob" %>
    <% if dob_was_invalid %>
      <% director.errors.full_messages_for(:dob).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = director.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% director.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% bio_class = "form-control" %>
    <% bio_was_invalid = director.errors.include?(:bio) %>

    <% if was_validated %>
      <% if bio_was_invalid %>
        <% bio_class << " is-invalid" %>
      <% else %>
        <% bio_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :bio %>
    <%= f.text_field :bio, class: bio_class, placeholder: "Enter bio" %>
    <% if bio_was_invalid %>
      <% director.errors.full_messages_for(:bio).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = director.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.text_field :image, class: image_class, placeholder: "Enter image" %>
    <% if image_was_invalid %>
      <% director.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% number_of_film_class = "form-control" %>
    <% number_of_film_was_invalid = director.errors.include?(:number_of_film) %>

    <% if was_validated %>
      <% if number_of_film_was_invalid %>
        <% number_of_film_class << " is-invalid" %>
      <% else %>
        <% number_of_film_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :number_of_films %>
    <%= f.number_field :number_of_films, class: number_of_film_class, placeholder: "Enter number of film" %>
    <% if number_of_film_was_invalid %>
      <% director.errors.full_messages_for(:number_of_film).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/directors/_list_item.html.erb
<%= link_to director, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= director %>
    <small class="text-muted">
      <%= time_ago_in_words(director.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/directors/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Director #<%= @director.id %>
      </h2>

      <div class="card-body">
        <%= render "form", director: @director %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/directors/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Directors

      <%= link_to new_director_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Directors

        <%= link_to new_director_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @directors, partial: "list_item", as: :director %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @directors, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/directors/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Director
      </h2>

      <div class="card-body">
        <%= render "form", director: @director %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/directors/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @director, partial: "card", as: :director %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "directors/director_reviews" %>
  </div>
</div>